FROM node:17.6-alpine3.14

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json

RUN apk add --no-cache --virtual .gyp \
    python3 \
    make \
    g++ \
    && npm ci \
    && npm rebuild node-sass \
    && npm install react-scripts@3.3.0 -g --silent \
    && apk del .gyp

RUN npm rebuild node-sass

COPY ./ /usr/src/app
ARG REACT_APP_RESERVATIONS_URL
ENV REACT_APP_RESERVATIONS_URL $REACT_APP_RESERVATIONS_URL

CMD ["npm", "start"]